---
- name: Remove Foreman provisioning callback
  lineinfile:
    path: /etc/rc.d/rc.local
    state: absent
    regexp: '^wget'
- name: Install Katello consumer
  yum: 
    name: https://{{ foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm 
    state: present
    validate_certs: no
- name: Subscribe to Katello
  command: subscription-manager register --org="{{ org }}" --activationkey="{{ activation_key }}" --force
- name: Restore CentOS branding
  command: yum -y reinstall centos-release
- name: Install Katello clients
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - katello-host-tools
    - katello-agent
- name: install Pupet Agent
  package:
    name: puppet-agent
    state: present
- name: Run Puppet Agent for the first time
  command: /opt/puppetlabs/bin/puppet agent -t --server {{ foreman_server }}

